### ISSUE TITLE
Mat files generation

### ISSUE THREAD

**Issue by Haitham96** [clinplayer/SEG-MAT#1]
Hi,

I tried to find an implementation to Q-Mat to generate Mat files for my mesh. But, unfortunately, I didn't find it.
Is there any way to generate these mat/smat files?

Thanks a lot,

Haitham

**Comment by clinplayer** [comment]
Hi, I can only provide an executable version that the authors released before [Q-Mat](https://drive.google.com/file/d/1cGYnTUquqA1kZFlOXBYLJKiGuAakNBRb/view?usp=sharing). If you want the source code, you can ask the authors of Q-Mat for help.

**Comment by clinplayer** [comment]
Hi, I added link to Q-MAT executable program and source code. https://drive.google.com/drive/folders/1cu9UNAUKgBwQpdBQPEeMT7k6ZKj6eRMz?usp=sharing

**Comment by Haitham96** [comment]
Thank you, very much

**Comment by aaoobd3** [comment]
hello can you please re upload the q mat executable file (i think it's deleted from google drive or moved to trash )
