### ISSUE TITLE
Qmat executable is deleted 

### ISSUE THREAD

**Issue by aaoobd3** [clinplayer/SEG-MAT#4]
hello can you please re upload the q mat executable file (i think it's deleted from google drive or moved to trash )

**Comment by clinplayer** [comment]
Please download it [here](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/chlin_connect_hku_hk/EQ7qXlADSq5IuseCeCqMPncBbwOoDqRYrTgKEKolrfOUpA?e=UZbK8d). I will update the links to these resources soon.
